all:
	mpirun -n 9 ./mpi_linear_regression > 1.txt	
	mpirun -n 9 ./mpi_linear_regression > 2.txt	
	mpirun -n 9 ./mpi_linear_regression > 3.txt	
	mpirun -n 9 ./mpi_linear_regression > 4.txt	
	mpirun -n 9 ./mpi_linear_regression > 5.txt	
	mpirun -n 9 ./mpi_linear_regression > 6.txt	
	mpirun -n 9 ./mpi_linear_regression > 7.txt	
	mpirun -n 9 ./mpi_linear_regression > 8.txt	
	mpirun -n 9 ./mpi_linear_regression > 9.txt	
	mpirun -n 9 ./mpi_linear_regression > 10.txt	
	
	
